INSERT INTO author (created_at, updated_at, name) VALUES (current_timestamp, current_timestamp, 'Elyn R. Saks');
INSERT INTO book (created_at, updated_at, isbn, link, name, author_id) VALUES (current_timestamp, current_timestamp, '9781401309442','https://www.amazon.com/Center-Cannot-Hold-Journey-Through/dp/1401309445', 'My Journey Through Madness', 1);
INSERT INTO author (created_at, updated_at, name) VALUES (current_timestamp, current_timestamp, 'J.M. Lee');
INSERT INTO book (created_at, updated_at, isbn, link, name, author_id) VALUES (current_timestamp, current_timestamp, '1662505043','https://www.amazon.com/gp/product/B09PBJ813F/ref=s9_acss_bw_cg_bsmafr_2c1_w','Broken Summer', 2);
INSERT INTO author (created_at, updated_at, name) VALUES (current_timestamp, current_timestamp, 'Robert Bailey');
INSERT INTO book (created_at, updated_at, isbn, link, name, author_id) VALUES (current_timestamp, current_timestamp, 'B09DYFQPNX', 'https://www.amazon.com/gp/product/B09DYFQPNX/ref=s9_acss_bw_cg_bsmafr_1a1_w','Rich Blood', 3);
INSERT INTO author (created_at, updated_at, name) VALUES (current_timestamp, current_timestamp, 'Roland Merullo');
INSERT INTO book (created_at, updated_at, isbn, link, name, author_id) VALUES (current_timestamp, current_timestamp, '1542034388', 'https://www.amazon.com/gp/product/B09G9YZ4V3/ref=s9_acss_bw_cg_bsmafr_1d1_w', 'A Harvest of Secrets', 4);
INSERT INTO book (created_at, updated_at, isbn, link, name, author_id) VALUES (current_timestamp, current_timestamp, '154201896X', 'https://www.amazon.com/gp/product/B086X2Z6RB/ref=dbs_a_def_rwt_bibl_vppi_i3', 'From These Broken Streets', 4);
INSERT INTO author (created_at, updated_at, name) VALUES (current_timestamp, current_timestamp, 'John Grisham');
INSERT INTO book (created_at, updated_at, isbn, link, name, author_id) VALUES (current_timestamp, current_timestamp, '1399708554', 'https://www.amazon.com/dp/B09QHKVGCJ/ref=s9_acsd_hps_bw_c2_x_1_t', 'Sparring Partners', 5);
INSERT INTO book (created_at, updated_at, isbn, link, name, author_id) VALUES (current_timestamp, current_timestamp, 'B087PKF9LZ', 'https://www.amazon.com/gp/product/B087PKF9LZ/ref=dbs_a_def_rwt_bibl_vppi_i3', 'A Time for Mercy', 5);
INSERT INTO book (created_at, updated_at, isbn, link, name, author_id) VALUES (current_timestamp, current_timestamp, 'B093F7SP44', 'https://www.amazon.com/gp/product/B093F7SP44/ref=dbs_a_def_rwt_bibl_vppi_i1', 'The Judges List', 5);
INSERT INTO author (created_at, updated_at, name) VALUES (current_timestamp, current_timestamp, 'Chris Bohjalian');
INSERT INTO book (created_at, updated_at, isbn, link, name, author_id) VALUES (current_timestamp, current_timestamp, 'B09CDB3DLY','https://www.amazon.com/dp/B09CDB3DLY/ref=s9_acsd_hps_bw_c2_x_4_i', 'The Lioness', 6);
INSERT INTO author (created_at, updated_at, name) VALUES (current_timestamp, current_timestamp, 'Richard Osman');
INSERT INTO book (created_at, updated_at, isbn, link, name, author_id) VALUES (current_timestamp, current_timestamp, 'B084M663VB', 'https://www.amazon.com/dp/B084M663VB/ref=s9_acsd_hps_bw_c2_x_2_t', 'The Thursday Murder Club', 7);
INSERT INTO author (created_at, updated_at, name) VALUES (current_timestamp, current_timestamp, 'Matt Haig');
INSERT INTO book (created_at, updated_at, isbn, link, name, author_id) VALUES (current_timestamp, current_timestamp, 'B072Q8WX9K', 'https://www.amazon.com/dp/B072Q8WX9K/ref=s9_acsd_hps_bw_c2_x_7_i', 'How to Stop Time', 8);
INSERT INTO book (created_at, updated_at, isbn, link, name, author_id) VALUES (current_timestamp, current_timestamp, 'B08M968WT1','https://www.amazon.com/gp/product/B08M968WT1/ref=dbs_a_def_rwt_bibl_vppi_i1', 'The Comfort Book', 8);
INSERT INTO book (created_at, updated_at, isbn, link, name, author_id) VALUES (current_timestamp, current_timestamp, 'B085BVSXS9','https://www.amazon.com/gp/product/B085BVSXS9/ref=dbs_a_def_rwt_bibl_vppi_i0', 'The Midnight Library', 8);

COMMIT;