server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/BookPortalDB
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        globally_quoted_identifiers: true
        enable_lazy_load_no_trans: true

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: health, info, metrics
logging:
  level:
    tr.com.obssintern: debug
    root: info

jwt:
  secret=javainuse: